alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias me="cd ~"
alias llamado-enfermeria="cd /media/juvasquezg/Netux/Proyectos/LlamadoEnfermeria/Desarrollo/Llamado_Enfermeria/"
